name: Deploy

on:
  push:
    branches:
    - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
name: Checkout
      uses: actions/checkout@v4

      
name: Conectar por SSH y desplegar
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.FRONTEND_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/repo || git clone https://github.com/elpanxo/notara-frontend.git repo
          cd repo
          git pull
          docker compose down
          docker compose up -d --build