name: Deploy Data Layer

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy en EC2 usando SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_DATA_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Docker Compose" \
            --parameters commands='[
              "cd /home/ec2-user",
              "if [ ! -d repo ]; then git clone https://github.com/elpanxo/notara-frontend.git repo; else cd repo && git pull && cd ..; fi",
              "cd repo",
              "echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} > .env",
              "docker compose down",
              "docker compose pull",
              "docker compose up -d"
            ]'
